### PR TITLE
Add vuido

### PR DESCRIPTION
**Pull request by parro-it**
vuido is platform based on libui-node and vue.js.
/CC @mimecorg

### CODE REVIEW

**Comment by mimecorg** [comment]
It would be great to add launchui-packager to the Packaging section as well.

**Comment by parro-it** [comment]
> It would be great to add launchui-packager to the Packaging section as well.

Would you mind to write a PR yourself? I'm waiting for mines to be merged to avoid doing a mess with my fork...

**Comment by styfle** [comment]
Thanks! 🎉

**Comment by styfle** [comment]
@parro-it I haven't tried out vuido but does it allow you to use CSS and render things the same in the browser as on the desktop?

**Comment by parro-it** [comment]
Not ATM. It's based on libui like proton

**Pull request merged**
