### PR TITLE
Changed sections, added another qt based one and fixed yue description.

### PR DESCRIPTION
**Pull request by Darkle**
Seems that Yue uses native APIs to draw the UI on each OS, rather than Electron: https://github.com/yue/yue/issues/49

### CODE REVIEW

**Comment by styfle** [comment]
@Darkle Thanks for the PR!
Can you change the description into one concise sentence?

```
a GUI with Node.js bindings to build cross-platform desktop apps using GDI+ on Windows, Cocoa on MacOS, GTK on Linux to render the UI
```

Also, does Yue belong in the UI Frameworks section? It seems like it doesn't use HTML/CSS as far as I can tell?

**Comment by Darkle** [comment]
> Also, does Yue belong in the UI Frameworks section? It seems like it doesn't use HTML/CSS as far as I can tell?

I'm wondering if we should change the section names. What about if we changed Web Frameworks to Web GUI Frameworks and changed UI Frameworks to Misc GUI Frameworks.

Or perhaps, since I just found [another](https://github.com/freemountain/quark/) QT based one (which is funnily enough also called quark), what if we did something like this:

## GUI Frameworks

* ### Electron/Chromium
	* [Electron](https://github.com/electron/electron) - a Node.js and Chromium runtime to build cross platform desktop apps
	* [nw.js](https://github.com/nwjs/nw.js) - a Node.js and Chromium runtime to build cross platform desktop apps
	* [Thrust](https://github.com/breach/thrust) - a Node.js and Chromium runtime to build cross platform desktop apps
* ## Misc. HTML
	* [Electrino](https://github.com/pojala/electrino) - a runtime to build cross platform desktop apps using the system's own web browser engine (Mac OS only)
	* [Quark Shell](https://github.com/HackPlan/quark-shell-mac) - a runtime to build cross platform desktop apps using the system's own web browser engine (Mac OS only)
	* [Quark](https://github.com/jscherer92/Quark) - a runtime to build cross platform desktop apps using the system's own web browser engine (Windows only)

* ## LibUI
	* [libui-node](https://github.com/parro-it/libui-node) - Node.js native desktop GUI framework to build cross-platform (Windows, macOS, Linux) apps.
	* [proton-native](https://github.com/kusti8/proton-native) a React.js environment to build cross platform native desktop apps
	* [vuido](https://github.com/mimecorg/vuido) - a Vue.js environment to build cross platform native desktop apps

* ## QT
	* [Brig](https://github.com/BrigJS/brig) - a user interface toolkit based on Qt to build cross-platform apps
	* [Quark](https://github.com/freemountain/quark/) another one

* ## Flexbox
	* [Yoga](https://github.com/facebook/yoga) - a layout engine which implements Flexbox to build cross-platform (node, browser asm, and standalone) apps

* ## GDI+/Cocoa/GTK
	* [Yue](https://github.com/yue/yue) - a library for creating native cross-platform desktop apps with Chromium

## System Tray

* [trayballoon](https://github.com/sindresorhus/trayballoon) - a system tray balloon on Windows
* [systray](https://github.com/zaaack/node-systray) - a system tray icon and menu that runs on Windows, Mac, Linux
* [menubar](https://github.com/maxogden/menubar) - easily create a menubar Electron app on MacOS
* [xtray](https://github.com/tetsuo/xtray) - create a native menubar app on MacOS via a node.js ⇆ Swift bridge using objc runtime
* [positron-bar](https://github.com/ElessarWebb/positron-bar) - Electron bar for your linux desktop

## Packaging

* [nexe](https://github.com/nexe/nexe) - a cli which compiles your Node.js app into a single executable
* [pkg](https://github.com/zeit/pkg) - a cli which compiles your Node.js app into a single executable
* [node-packer](https://github.com/pmq20/node-packer) - a cli which compiles your Node.js app into a single executable
* [nectarjs](https://github.com/NectarJS/nectarjs) - a cli which compiles your Node.js app into a single executable (linux, windows, wasm, asm, arduino)
* [lone](https://github.com/imlucas/lone) - a cli which compiles your Node.js app into a single executable
* [launchui-packager](https://github.com/mimecorg/launchui-packager) - an API which packages GUI Node.js applications for Windows, Linux and OS X



The GDI+/Cocoa/GTK section may not be great, but the others look good. What do you think? 🤔

Edit: I suppose technically we could put Yue in the Flexbox section since it does use yoga which is Flexbox.

**Comment by styfle** [comment]
Great job! I really like this organization 🎉 

> I suppose technically we could put Yue in the Flexbox section since it does use yoga which is Flexbox.

Let's put Yue under the Flexbox section for now.

Would you like to submit a new PR or modify this one?

**Comment by Darkle** [comment]
> Would you like to submit a new PR or modify this one?

I've modified this one.

**Comment by styfle** [comment]
Thanks this is great! 💯

**Pull request merged**
